ort:
  
  enableRepositoryPackageConfigurations: true
  enableRepositoryPackageCurations: true

  # Force overwriting of any existing output files.
  forceOverwrite: true

  licenseFilePatterns:
    licenseFilenames: ['license*']
    patentFilenames: ['patents']
    otherLicenseFilenames: ['readme*']


  severeIssueThreshold: ERROR
  severeRuleViolationThreshold: ERROR

analyzer:
    
    # A flag to control whether excluded scopes and paths should be skipped during the analysis.
    skipExcluded: true

    allowDynamicVersions: true

    # A list of enabled package managers.
    enabledPackageManagers: [Gradle, Maven, NPM]

advisor:
    # A flag to control whether excluded scopes and paths should be skipped when giving the advice.
    skipExcluded: true

    config:
      OSV:
        options:
          serverUrl: 'https://api.osv.dev'

downloader:
    allowMovingRevisions: true

    # Only used if the '--license-classifications-file' option is specified.
    includedLicenseCategories:
      - 'category-a'
      - 'category-b'

    # A flag to control whether excluded scopes and paths should be skipped during the download.
    skipExcluded: true

    sourceCodeOrigins: [VCS, ARTIFACT]

scanner:
    
    skipExcluded: true

    config:
      # A map from scanner plugin types to the plugin configuration.
      ScanCode:
        options:
          # Command line options that affect the ScanCode output. If changed, stored scan results that were created with
          # different options are not reused.
          commandLine: '--copyright --license --info --strip-root --timeout 300 --ignore README --ignore package.json'

          # Command line options that do not affect the ScanCode output.
          commandLineNonConfig: '--processes 4'

    archive:
      enabled: true

    #   fileStorage:
    #     localFileStorage:
    #       directory: ~/Documents/Enterprise-OSO/Tooling/ORT/fileStorage/archive
    #       compression: false

      postgresStorage:
        connection:
          url: 'jdbc:postgresql://oss-ort-db-oss-ort-db.i.aivencloud.com:14997/defaultdb'
          schema: public
          username: avnadmin
          password: AVNS_5OmJyeqijnVyfacbzcP
          sslmode: require
          sslrootcert: /ca.pem
          connectionTimeout: 30000
          idleTimeout: 600000
          keepaliveTime: 0
          maxLifetime: 1800000
          maximumPoolSize: 10
          minimumIdle: 600000
    
    detectedLicenseMapping:
      BSD (Three Clause License): 'BSD-3-clause'
      LicenseRef-scancode-generic-cla: 'NOASSERTION'

    # fileListStorage:
    #   fileStorage:
    #     localFileStorage:
    #       directory: ~/Documents/Enterprise-OSO/Tooling/ORT/fileStorage/file-lists
    #       compression: false
    
    # storages:
    #  local:
    #     backend:
    #       localFileStorage:
    #         directory: ~/Documents/Enterprise-OSO/Tooling/ORT/fileStorage/results
    #         compression: false

      SCANOSS:
        options:
          apiUrl: 'https://api.osskb.org/'
      
      clearlyDefined:
        serverUrl: 'https://api.clearlydefined.io'
    
    # Storage readers are listed from highest to lower priority, i.e. the first match wins.
    storageReaders: [postgres,  clearlyDefined, scanoss]

    # For storage writers no priority is implied by the order; scan results are stored for all writers.
    storageWriters: [postgres]

    ignorePatterns: ['**/META-INF/DEPENDENCIES']

    # provenanceStorage:
    #   fileStorage:
    #     localFileStorage:
    #       directory: ~/Documents/Enterprise-OSO/Tooling/ORT/fileStorage/provenance
    #       compression: false
